# Generated by Django 2.1.4 on 2018-12-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'List of Blocks and respective Floors',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'List of Floors',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('room_status', models.BooleanField(default=0)),
                ('block_floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RoomsManagement.BlockFloor')),
            ],
            options={
                'db_table': 'Assigned Rooms',
            },
        ),
        migrations.AlterOrderWithRespectTo(
            name='room',
            order_with_respect_to='room_status',
        ),
        migrations.AddField(
            model_name='blockfloor',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RoomsManagement.Floor'),
        ),
    ]
