# Generated by Django 2.1.4 on 2018-12-17 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomsManagement', '0001_initial'),
        ('Customers', '0002_auto_20181217_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone_number', models.BigIntegerField()),
                ('number_of_visits', models.IntegerField()),
                ('assigned_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RoomsManagement.Room')),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='number_of_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customers',
            name='room_assigned_deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 16, 50, 13, 614658), editable=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='room_assigned_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
