# Generated by Django 2.1.4 on 2018-12-17 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_auto_20181217_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='room_assigned_deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 16, 52, 12, 692753), editable=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='room_assigned_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 16, 52, 12, 692753), editable=False),
        ),
    ]
