# Generated by Django 2.1.4 on 2018-12-17 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_auto_20181217_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='room_assigned_deadline',
        ),
        migrations.AlterField(
            model_name='customers',
            name='room_assigned_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 16, 54, 55, 929027), editable=False),
        ),
    ]
