# Generated by Django 2.1.4 on 2018-12-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Food Categories',
            },
        ),
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Food Items Table',
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_available', models.CharField(max_length=20)),
                ('item_required', models.CharField(max_length=20)),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodService.FoodCategory')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodService.FoodItems')),
            ],
            options={
                'db_table': 'Food Database Table',
            },
        ),
        migrations.CreateModel(
            name='FoodTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Food Types Table',
            },
        ),
        migrations.AddField(
            model_name='foods',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodService.FoodTypes'),
        ),
    ]
