# Generated by Django 2.1.4 on 2018-12-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'List of Blocks and respective Floors',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'List of Floors',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('booked_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('booked_hours', models.IntegerField(blank=True, default=0, null=True)),
                ('block_floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RoomService.BlockFloor')),
                ('booked_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Customers.Customers')),
            ],
            options={
                'db_table': 'Assigned Rooms',
            },
        ),
        migrations.AddField(
            model_name='blockfloor',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RoomService.Floor'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='room',
            order_with_respect_to='block_floor',
        ),
    ]
